server {

    listen 80;

    # teste api - acessar localhost
    location / {
        proxy_pass http://app-java:8080;
    }

    # phpMyAdmin - acessar localhost/admin
    location /admin/ {
        proxy_pass http://phpmyadmin:80/;
    }
}